### ISSUE TITLE
Considering redoing this example with the native rust_xlsxwriter

### ISSUE THREAD

**Issue by jmcnamara** [zupzup/xlsx-in-rust-example#1]
Hi,

I liked your post on [Creating Excel files in Rust](https://www.zupzup.org/xlsx-in-rust/). I wrote the libxlsxwriter C library that xlsxwriter.rs wraps and I'm currently porting it to rust: https://crates.io/crates/rust_xlsxwriter

If you get some spare cycles you could try it out and so how it compares. In relation to your article the interfaces are very similar and it already has chrono support and a simulates autofit.

John

**Comment by zupzup** [comment]
Hey John,

Thanks for mentioning this, that's so cool!

I'm a bit busy at the moment, but it's definitely on my TODO list now :)

**Comment by jmcnamara** [comment]
Thank you. There is no rush. :-)

Closing.
